<a href="https://colab.research.google.com/github/samuelpolontalo/Analisis_Kemacetan_Jakarta/blob/main/Analisis_Kemacetan_Jakarta.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import requests
import urllib.parse as urlparse
import datetime
import matplotlib.pyplot as plt

In [4]:
# response = requests.get("https://api.tomtom.com/routing/1/calculateRoute/-6.2475352238102175%2C106.83054513451853%3A-6.217161831482172%2C106.8149044119333/json?traffic=true&key=KYii8cuAgfaLwacGfVfEmmkDSkwt5w2D")
# response_json = response.json()
# print(response_json)

{'formatVersion': '0.0.12', 'routes': [{'summary': {'lengthInMeters': 6293, 'travelTimeInSeconds': 1152, 'trafficDelayInSeconds': 205, 'trafficLengthInMeters': 1021, 'departureTime': '2022-07-28T16:57:21+07:00', 'arrivalTime': '2022-07-28T17:16:33+07:00'}, 'legs': [{'summary': {'lengthInMeters': 6293, 'travelTimeInSeconds': 1152, 'trafficDelayInSeconds': 205, 'trafficLengthInMeters': 1021, 'departureTime': '2022-07-28T16:57:21+07:00', 'arrivalTime': '2022-07-28T17:16:33+07:00'}, 'points': [{'latitude': -6.24742, 'longitude': 106.83055}, {'latitude': -6.24741, 'longitude': 106.831}, {'latitude': -6.24741, 'longitude': 106.83105}, {'latitude': -6.24741, 'longitude': 106.83118}, {'latitude': -6.2474, 'longitude': 106.8312}, {'latitude': -6.24739, 'longitude': 106.83123}, {'latitude': -6.24735, 'longitude': 106.83124}, {'latitude': -6.24719, 'longitude': 106.83126}, {'latitude': -6.24701, 'longitude': 106.83126}, {'latitude': -6.24685, 'longitude': 106.83125}, {'latitude': -6.24664, 'longitude': 106.83121}, {'latitude': -6.24663, 'longitude': 106.83151}, {'latitude': -6.24661, 'longitude': 106.83172}, {'latitude': -6.24661, 'longitude': 106.83213}, {'latitude': -6.24655, 'longitude': 106.83213}, {'latitude': -6.24595, 'longitude': 106.83216}, {'latitude': -6.24571, 'longitude': 106.83218}, {'latitude': -6.24522, 'longitude': 106.8322}, {'latitude': -6.2449, 'longitude': 106.83222}, {'latitude': -6.24461, 'longitude': 106.83223}, {'latitude': -6.24396, 'longitude': 106.83228}, {'latitude': -6.2431, 'longitude': 106.83231}, {'latitude': -6.24288, 'longitude': 106.83234}, {'latitude': -6.2425, 'longitude': 106.83236}, {'latitude': -6.24222, 'longitude': 106.8324}, {'latitude': -6.24187, 'longitude': 106.83248}, {'latitude': -6.2414, 'longitude': 106.83256}, {'latitude': -6.24116, 'longitude': 106.83258}, {'latitude': -6.24054, 'longitude': 106.83258}, {'latitude': -6.24044, 'longitude': 106.8326}, {'latitude': -6.24023, 'longitude': 106.83225}, {'latitude': -6.24023, 'longitude': 106.83224}, {'latitude': -6.24001, 'longitude': 106.83186}, {'latitude': -6.23994, 'longitude': 106.83176}, {'latitude': -6.23963, 'longitude': 106.83131}, {'latitude': -6.23956, 'longitude': 106.8312}, {'latitude': -6.23946, 'longitude': 106.83105}, {'latitude': -6.23926, 'longitude': 106.83077}, {'latitude': -6.2391, 'longitude': 106.83048}, {'latitude': -6.23871, 'longitude': 106.82987}, {'latitude': -6.23866, 'longitude': 106.82974}, {'latitude': -6.23845, 'longitude': 106.82938}, {'latitude': -6.23834, 'longitude': 106.82932}, {'latitude': -6.23827, 'longitude': 106.82919}, {'latitude': -6.23762, 'longitude': 106.82812}, {'latitude': -6.23748, 'longitude': 106.82791}, {'latitude': -6.23705, 'longitude': 106.82722}, {'latitude': -6.23702, 'longitude': 106.82718}, {'latitude': -6.23697, 'longitude': 106.8271}, {'latitude': -6.23695, 'longitude': 106.82707}, {'latitude': -6.23665, 'longitude': 106.82664}, {'latitude': -6.2364, 'longitude': 106.82627}, {'latitude': -6.23611, 'longitude': 106.82582}, {'latitude': -6.23566, 'longitude': 106.82515}, {'latitude': -6.23534, 'longitude': 106.82466}, {'latitude': -6.23528, 'longitude': 106.82457}, {'latitude': -6.23501, 'longitude': 106.82417}, {'latitude': -6.23474, 'longitude': 106.8237}, {'latitude': -6.23412, 'longitude': 106.82269}, {'latitude': -6.23368, 'longitude': 106.82213}, {'latitude': -6.23341, 'longitude': 106.82186}, {'latitude': -6.23316, 'longitude': 106.82163}, {'latitude': -6.23303, 'longitude': 106.82152}, {'latitude': -6.23225, 'longitude': 106.82088}, {'latitude': -6.23009, 'longitude': 106.81939}, {'latitude': -6.22928, 'longitude': 106.81884}, {'latitude': -6.22764, 'longitude': 106.81772}, {'latitude': -6.22756, 'longitude': 106.81767}, {'latitude': -6.22664, 'longitude': 106.81705}, {'latitude': -6.22647, 'longitude': 106.81695}, {'latitude': -6.22637, 'longitude': 106.81687}, {'latitude': -6.22601, 'longitude': 106.81662}, {'latitude': -6.22494, 'longitude': 106.81592}, {'latitude': -6.22362, 'longitude': 106.81495}, {'latitude': -6.22355, 'longitude': 106.81489}, {'latitude': -6.22339, 'longitude': 106.81479}, {'latitude': -6.223, 'longitude': 106.81454}, {'latitude': -6.22297, 'longitude': 106.81452}, {'latitude': -6.2228, 'longitude': 106.81444}, {'latitude': -6.22271, 'longitude': 106.81439}, {'latitude': -6.22246, 'longitude': 106.81421}, {'latitude': -6.22193, 'longitude': 106.81386}, {'latitude': -6.22162, 'longitude': 106.81364}, {'latitude': -6.22128, 'longitude': 106.8134}, {'latitude': -6.22117, 'longitude': 106.81333}, {'latitude': -6.22101, 'longitude': 106.81302}, {'latitude': -6.2209, 'longitude': 106.81277}, {'latitude': -6.22088, 'longitude': 106.81267}, {'latitude': -6.22083, 'longitude': 106.81225}, {'latitude': -6.22083, 'longitude': 106.81218}, {'latitude': -6.22082, 'longitude': 106.81211}, {'latitude': -6.22079, 'longitude': 106.81204}, {'latitude': -6.22073, 'longitude': 106.8119}, {'latitude': -6.22055, 'longitude': 106.81158}, {'latitude': -6.22034, 'longitude': 106.81135}, {'latitude': -6.22029, 'longitude': 106.81132}, {'latitude': -6.22026, 'longitude': 106.8113}, {'latitude': -6.22021, 'longitude': 106.81127}, {'latitude': -6.22009, 'longitude': 106.8112}, {'latitude': -6.21987, 'longitude': 106.81109}, {'latitude': -6.2197, 'longitude': 106.81104}, {'latitude': -6.21945, 'longitude': 106.81101}, {'latitude': -6.21919, 'longitude': 106.81101}, {'latitude': -6.21905, 'longitude': 106.81103}, {'latitude': -6.21894, 'longitude': 106.81105}, {'latitude': -6.2187, 'longitude': 106.81114}, {'latitude': -6.21848, 'longitude': 106.81127}, {'latitude': -6.21841, 'longitude': 106.81132}, {'latitude': -6.21833, 'longitude': 106.81139}, {'latitude': -6.21826, 'longitude': 106.81146}, {'latitude': -6.21823, 'longitude': 106.81149}, {'latitude': -6.21815, 'longitude': 106.8116}, {'latitude': -6.21808, 'longitude': 106.81171}, {'latitude': -6.21801, 'longitude': 106.81187}, {'latitude': -6.21798, 'longitude': 106.81197}, {'latitude': -6.21795, 'longitude': 106.81214}, {'latitude': -6.21795, 'longitude': 106.81233}, {'latitude': -6.21795, 'longitude': 106.81251}, {'latitude': -6.21795, 'longitude': 106.8126}, {'latitude': -6.21802, 'longitude': 106.81347}, {'latitude': -6.21802, 'longitude': 106.81358}, {'latitude': -6.218, 'longitude': 106.81384}, {'latitude': -6.21793, 'longitude': 106.81404}, {'latitude': -6.21788, 'longitude': 106.81413}, {'latitude': -6.21742, 'longitude': 106.81473}, {'latitude': -6.2171, 'longitude': 106.81501}, {'latitude': -6.21704, 'longitude': 106.81508}, {'latitude': -6.21699, 'longitude': 106.81515}, {'latitude': -6.21687, 'longitude': 106.81531}, {'latitude': -6.21678, 'longitude': 106.81542}, {'latitude': -6.21672, 'longitude': 106.81549}, {'latitude': -6.21667, 'longitude': 106.81556}, {'latitude': -6.21664, 'longitude': 106.81561}, {'latitude': -6.2166, 'longitude': 106.81566}, {'latitude': -6.21656, 'longitude': 106.81572}, {'latitude': -6.21622, 'longitude': 106.8162}, {'latitude': -6.21568, 'longitude': 106.81579}, {'latitude': -6.21554, 'longitude': 106.81568}, {'latitude': -6.21507, 'longitude': 106.8153}, {'latitude': -6.21494, 'longitude': 106.81519}, {'latitude': -6.21469, 'longitude': 106.815}, {'latitude': -6.21453, 'longitude': 106.81489}, {'latitude': -6.21449, 'longitude': 106.8148}, {'latitude': -6.21453, 'longitude': 106.81474}, {'latitude': -6.21493, 'longitude': 106.81431}, {'latitude': -6.21531, 'longitude': 106.81393}, {'latitude': -6.21556, 'longitude': 106.81416}, {'latitude': -6.2156, 'longitude': 106.81421}, {'latitude': -6.21572, 'longitude': 106.8143}, {'latitude': -6.21626, 'longitude': 106.81362}, {'latitude': -6.21632, 'longitude': 106.81355}, {'latitude': -6.21642, 'longitude': 106.81343}, {'latitude': -6.2177, 'longitude': 106.81183}, {'latitude': -6.21776, 'longitude': 106.81174}, {'latitude': -6.21783, 'longitude': 106.81198}, {'latitude': -6.21785, 'longitude': 106.81211}, {'latitude': -6.21788, 'longitude': 106.81251}, {'latitude': -6.21795, 'longitude': 106.81353}, {'latitude': -6.21794, 'longitude': 106.81368}, {'latitude': -6.21792, 'longitude': 106.81375}, {'latitude': -6.21788, 'longitude': 106.8139}, {'latitude': -6.21783, 'longitude': 106.81402}, {'latitude': -6.21753, 'longitude': 106.81442}, {'latitude': -6.21744, 'longitude': 106.81453}, {'latitude': -6.21719, 'longitude': 106.8149}]}], 'sections': [{'startPointIndex': 0, 'endPointIndex': 164, 'sectionType': 'TRAVEL_MODE', 'travelMode': 'car'}]}]}

In [5]:
# summary = response_json['routes'][0]['summary']
# for each_summary in summary:
#   print(each_summary)

lengthInMeters
travelTimeInSeconds
trafficDelayInSeconds
trafficLengthInMeters
departureTime
arrivalTime

In [2]:
start = "-6.2475352238102175,106.83054513451853"               # kosan
end = "-6.217161831482172,106.8149044119333"                # kantor
key = "KYii8cuAgfaLwacGfVfEmmkDSkwt5w2D"             # API Key
 
# Base URL
base_url = "https://api.tomtom.com/routing/1/calculateRoute/"

In [7]:
date = datetime.datetime(2019, 1, 1)
departure_time_start2021 = datetime.datetime(date.year, date.month , date.day, 6, 0, 0)
print (departure_time_start2021)
month_range = range(0,12)
day_range = range (0,26)
 
for i in month_range:
    for j in day_range:
      # Update the month
      departure_time2021= departure_time_start2021.replace(month=departure_time_start2021.month + i, day=departure_time_start2021.day +j)
      # Format datetime string
      departure_time2021 = departure_time2021.strftime('%Y-%m-%dT%H:%M:%S')   
  
      # Create request URL
      request_params2021 = (
          urlparse.quote(start) + ":" + urlparse.quote(end) 
          + "/json?departAt=" + urlparse.quote(departure_time2021))

      request_url2021 = base_url + request_params2021 + "&key=" + key

      # Get data
      response2021 = requests.get(request_url2021)
      if response2021.status_code != 200:
        continue
  
      # Convert to JSON
      json_result2021 = response2021.json()
      
      # Get summary
      route_summary2021 = json_result2021['routes'][0]['summary']
      
      # Convert to data frame and append
      if((i == 0) and (j==0)):
          df2021 = pd.json_normalize(route_summary2021)
      else:
          df2021 = df2021.append(pd.json_normalize(route_summary2021), ignore_index=True)    
        
    print(f"Retrieving data: {i+1} / {len(month_range)}")

2019-01-01 06:00:00
Retrieving data: 1 / 12
Retrieving data: 2 / 12
Retrieving data: 3 / 12
Retrieving data: 4 / 12
Retrieving data: 5 / 12
Retrieving data: 6 / 12
Retrieving data: 7 / 12
Retrieving data: 8 / 12
Retrieving data: 9 / 12
Retrieving data: 10 / 12
Retrieving data: 11 / 12
Retrieving data: 12 / 12

In [8]:
df2021

,lengthInMeters,travelTimeInSeconds,trafficDelayInSeconds,trafficLengthInMeters,departureTime,arrivalTime
0,6291,749,0,0,2019-01-01T06:00:00+07:00,2019-01-01T06:12:29+07:00
1,6291,743,0,0,2019-01-02T06:00:00+07:00,2019-01-02T06:12:22+07:00
2,6511,764,0,0,2019-01-03T06:00:00+07:00,2019-01-03T06:12:44+07:00
3,6291,755,0,0,2019-01-04T06:00:00+07:00,2019-01-04T06:12:34+07:00
4,6291,729,0,0,2019-01-05T06:00:00+07:00,2019-01-05T06:12:09+07:00
...,...,...,...,...,...,...
145,6291,747,0,0,2019-12-16T06:00:00+07:00,2019-12-16T06:12:27+07:00
146,6291,749,0,0,2019-12-17T06:00:00+07:00,2019-12-17T06:12:29+07:00
147,6291,749,0,0,2019-12-24T06:00:00+07:00,2019-12-24T06:12:29+07:00
148,6291,743,0,0,2019-12-25T06:00:00+07:00,2019-12-25T06:12:22+07:00
149,6511,764,0,0,2019-12-26T06:00:00+07:00,2019-12-26T06:12:44+07:00